### ISSUE TITLE
zsh: no matches found: EXTRA_EXPORTED_RUNTIME_METHODS=[ccall,UTF8ToString]

### ISSUE THREAD

**Issue by gwsounddsg** [gwsounddsg/WasmTesting#2]
In the current main branch, running the following command `emcc validate.cpp -o -valids.js -s EXTRA_EXPORTED_RUNTIME_METHODS=['ccall','UTF8ToString']` gives me an error.

**Comment by adam-cyclones** [comment]
Il look into it ASAP, also the emscripten discord is pretty great if your in a hurry.

https://discord.com/invite/53u3EKq

**Comment by gwsounddsg** [comment]
Yup, I posted one question there already. Waiting to hear back.

**Comment by gwsounddsg** [comment]
Someone responded to my question on discord. They suggested I prefix the whole command with `noglob` and it worked!
